<a href="https://colab.research.google.com/github/KHarikrishna2006/DATA_ANALYTICS/blob/main/DA_LAB_INTRENAL_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
dic={
    "Name":["Hari","Krishna","Manoj","Akhil","Akhil"],
    "Age":[18,180,19,20,np.nan],
    "Salary":[100000,200000,35000,75000,20000]
}
df=pd.DataFrame(dic)
df

      Name    Age  Salary
0     Hari   18.0  100000
1  Krishna  180.0  200000
2    Manoj   19.0   35000
3    Akhil   20.0   75000
4    Akhil    NaN   20000

In [3]:
#Missing values
df_droped=df.dropna()
print("Dataset After droping null values")
df_droped

Dataset After droping null values

      Name    Age  Salary
0     Hari   18.0  100000
1  Krishna  180.0  200000
2    Manoj   19.0   35000
3    Akhil   20.0   75000

In [4]:
m=df['Age'].median()
m=int(m)
df['Age']=df['Age'].fillna(m)
print("Imputation in missing values")
df

Imputation in missing values

      Name    Age  Salary
0     Hari   18.0  100000
1  Krishna  180.0  200000
2    Manoj   19.0   35000
3    Akhil   20.0   75000
4    Akhil   19.0   20000

In [5]:
df=df.sort_values(by='Age')
q1=df['Age'].quantile(0.25)
q3=df['Age'].quantile(0.75)
IQR=q3-q1
l=q1-1.5*IQR
u=q3+1.5*IQR
Clen_df=df[(df['Age']>=l) & (df['Age']<=u)]
print("dTASET aFTER REMOVING TRTHE oYTLIERS")
Clen_df

dTASET aFTER REMOVING TRTHE oYTLIERS

    Name   Age  Salary
0   Hari  18.0  100000
2  Manoj  19.0   35000
4  Akhil  19.0   20000
3  Akhil  20.0   75000

In [6]:
final_df=Clen_df.drop_duplicates(keep='first')
print("Final cleaned Dataset is")
final_df.dropna(inplace=True)
final_df

Final cleaned Dataset is

    Name   Age  Salary
0   Hari  18.0  100000
2  Manoj  19.0   35000
4  Akhil  19.0   20000
3  Akhil  20.0   75000